# fly.toml file generated for javaspring on 2023-03-27T07:21:57-03:00

app = "javaspring"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "gru"
processes = []

[env]
  DB_PASSWORD = "${DB_PASSWORD}"
  DB_URL = "${DATABASE_URL}"
  DB_USERNAME = "${DB_USERNAME}"
  JHIPSTER_SLEEP = 5
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED = "false"
  SPRING_PROFILES_ACTIVE = "prod"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
